name: Generate Dockerfile

on:
  repository_dispatch:
    types: [trigger-service]

jobs:
  generate-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Echo build process
        run: echo "Dockerfile generation triggered successfully!"
